# Header
menu:
  主页: /
  所有文章: /archives
  三国杀: /sgs
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/acshiryu/hexo"
  weibo: "http://weibo.com/acshiryu"
  rss: "/atom.xml"
  #zhihu: "#"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 


# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
#animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: /images/website/avatar.png
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: "acshiryu"
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  逗逼疯: http://wangwenfeng.com/
  Gavin: http://ligavin.net/


#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 小龙少，年二十有二。始从文，连考而不中。遂习武，练武场上发一矢，中鼓吏，逐之出。改学IT，自撰一函数，用之，堆栈溢出。

#是否开启搜索(使用Swiftype Search)
#true or false
search: true

#### Toc
#### from theme iceman
toc:
  article: true   ## show contents in article.
  aside: true     ## show contents in aside.
## you can set both of the value to true of neither of them.
## if you don't want display contents in a specified post,you can modify `front-matter` and add `toc: false`.